version: '2'
services:
  web:
    build: .
    ports:
      - "5000:80"
    links:
      - db
    volumes:
      - ./extensions:/var/www/flarum/extensions
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: flarum
      MYSQL_DATABASE: flarum
